development:
  adapter: postgresql
  host: localhost
  database: playerpool

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  host: localhost
  database: playerpool2013
